import {atom} from 'recoil'

export const jogadores_cadastrados = atom({
    key: "jogadores_cadastrados", default: [
        {
            id: 1,
            nome: 'Guilherme Borba',
            imagem_url: 'https://lh3.googleusercontent.com/u/0/drive-viewer/AK7aPaCmk4aqSoZiW92gW10vMY4ZpL_gpFIW6S9N2oqqApU_ieFuqjQcQpnHZeCeyX4uvOUelXX7K_e1iYcxeqLqDioexa_z=w1920-h943',
            fator_x: '2',
            numero_camisa: 20,
            pontuacao: 0,
            cestas_3: 0,
            cestas_2: 0,
            cestas_1: 0,
            faltas: 0,
            rebotes: 0,
            assistencias: 0,
            roubos: 0
        }, {
            id: 2,
            nome: 'Bruno Zamorano',
            imagem_url: 'https://lh3.googleusercontent.com/u/0/drive-viewer/AK7aPaCy9sEthqm8pg_PtUl1H3KM0XHRoixnho0Oe7g-sbK-SVNr52nc8wj1kJZEc9DBQxTf2jPDBNRtS47GWex4Iy1MGGDC4A=w1911-h958',
            fator_x: '5',
            numero_camisa: 76,
            pontuacao: 0,
            cestas_3: 0,
            cestas_2: 0,
            cestas_1: 0,
            faltas: 0,
            rebotes: 0,
            assistencias: 0,
            roubos: 0
        }, {
            id: 3,
            nome: 'Bruno Zamorano',
            imagem_url: 'https://lh3.googleusercontent.com/u/0/drive-viewer/AK7aPaCy9sEthqm8pg_PtUl1H3KM0XHRoixnho0Oe7g-sbK-SVNr52nc8wj1kJZEc9DBQxTf2jPDBNRtS47GWex4Iy1MGGDC4A=w1911-h958',
            fator_x: '6',
            numero_camisa: 76,
            pontuacao: 0,
            cestas_3: 0,
            cestas_2: 0,
            cestas_1: 0,
            faltas: 0,
            rebotes: 0,
            assistencias: 0,
            roubos: 0
        }, {
            id: 4,
            nome: 'Bruno Zamorano',
            imagem_url: 'https://lh3.googleusercontent.com/u/0/drive-viewer/AK7aPaCy9sEthqm8pg_PtUl1H3KM0XHRoixnho0Oe7g-sbK-SVNr52nc8wj1kJZEc9DBQxTf2jPDBNRtS47GWex4Iy1MGGDC4A=w1911-h958',
            fator_x: '10',
            numero_camisa: 76,
            pontuacao: 0,
            cestas_3: 0,
            cestas_2: 0,
            cestas_1: 0,
            faltas: 0,
            rebotes: 0,
            assistencias: 0,
            roubos: 0
        }, {
            id: 5,
            nome: 'Bruno Zamorano',
            imagem_url: 'https://lh3.googleusercontent.com/u/0/drive-viewer/AK7aPaCy9sEthqm8pg_PtUl1H3KM0XHRoixnho0Oe7g-sbK-SVNr52nc8wj1kJZEc9DBQxTf2jPDBNRtS47GWex4Iy1MGGDC4A=w1911-h958',
            fator_x: '4',
            numero_camisa: 76,
            pontuacao: 0,
            cestas_3: 0,
            cestas_2: 0,
            cestas_1: 0,
            faltas: 0,
            rebotes: 0,
            assistencias: 0,
            roubos: 0
        }, {
            id: 6,
            nome: 'Bruno Zamorano',
            imagem_url: 'https://lh3.googleusercontent.com/u/0/drive-viewer/AK7aPaCy9sEthqm8pg_PtUl1H3KM0XHRoixnho0Oe7g-sbK-SVNr52nc8wj1kJZEc9DBQxTf2jPDBNRtS47GWex4Iy1MGGDC4A=w1911-h958',
            fator_x: '8',
            numero_camisa: 76,
            pontuacao: 0,
            cestas_3: 0,
            cestas_2: 0,
            cestas_1: 0,
            faltas: 0,
            rebotes: 0,
            assistencias: 0,
            roubos: 0
        }, {
            id: 7,
            nome: 'Bruno Zamorano',
            imagem_url: 'https://lh3.googleusercontent.com/u/0/drive-viewer/AK7aPaCy9sEthqm8pg_PtUl1H3KM0XHRoixnho0Oe7g-sbK-SVNr52nc8wj1kJZEc9DBQxTf2jPDBNRtS47GWex4Iy1MGGDC4A=w1911-h958',
            fator_x: '6',
            numero_camisa: 76,
            pontuacao: 0,
            cestas_3: 0,
            cestas_2: 0,
            cestas_1: 0,
            faltas: 0,
            rebotes: 0,
            assistencias: 0,
            roubos: 0
        }, {
            id: 8,
            nome: 'Bruno Zamorano',
            imagem_url: 'https://lh3.googleusercontent.com/u/0/drive-viewer/AK7aPaCy9sEthqm8pg_PtUl1H3KM0XHRoixnho0Oe7g-sbK-SVNr52nc8wj1kJZEc9DBQxTf2jPDBNRtS47GWex4Iy1MGGDC4A=w1911-h958',
            fator_x: '12',
            numero_camisa: 76,
            pontuacao: 0,
            cestas_3: 0,
            cestas_2: 0,
            cestas_1: 0,
            faltas: 0,
            rebotes: 0,
            assistencias: 0,
            roubos: 0
        }, {
            id: 9,
            nome: 'Bruno Zamorano',
            imagem_url: 'https://lh3.googleusercontent.com/u/0/drive-viewer/AK7aPaCy9sEthqm8pg_PtUl1H3KM0XHRoixnho0Oe7g-sbK-SVNr52nc8wj1kJZEc9DBQxTf2jPDBNRtS47GWex4Iy1MGGDC4A=w1911-h958',
            fator_x: '7',
            numero_camisa: 76,
            pontuacao: 0,
            cestas_3: 0,
            cestas_2: 0,
            cestas_1: 0,
            faltas: 0,
            rebotes: 0,
            assistencias: 0,
            roubos: 0
        }, {
            id: 10,
            nome: 'Bruno Zamorano',
            imagem_url: 'https://lh3.googleusercontent.com/u/0/drive-viewer/AK7aPaCy9sEthqm8pg_PtUl1H3KM0XHRoixnho0Oe7g-sbK-SVNr52nc8wj1kJZEc9DBQxTf2jPDBNRtS47GWex4Iy1MGGDC4A=w1911-h958',
            fator_x: '7',
            numero_camisa: 76,
            pontuacao: 0,
            cestas_3: 0,
            cestas_2: 0,
            cestas_1: 0,
            faltas: 0,
            rebotes: 0,
            assistencias: 0,
            roubos: 0
        }]
});