import {atom} from 'recoil'

export const times_montados = atom({
    key: "times_montados", default: {
        time_a: [
            {
                id: 1,
                nome: 'insira um jogador',
                imagem_url: '+',
                fator_x: '2',
                numero_camisa: '+',
                pontuacao: 0,
                cestas_3: 0,
                cestas_2: 0,
                cestas_1: 0,
                faltas: 0,
                rebotes: 0,
                assistencias: 0,
                roubos: 0
            }, {
                id: 1,
                nome: 'insira um jogador',
                imagem_url: '',
                fator_x: '2',
                numero_camisa: '+',
                pontuacao: 0,
                cestas_3: 0,
                cestas_2: 0,
                cestas_1: 0,
                faltas: 0,
                rebotes: 0,
                assistencias: 0,
                roubos: 0
            }, {
                id: 1,
                nome: 'insira um jogador',
                imagem_url: '',
                fator_x: '2',
                numero_camisa: '+',
                pontuacao: 0,
                cestas_3: 0,
                cestas_2: 0,
                cestas_1: 0,
                faltas: 0,
                rebotes: 0,
                assistencias: 0,
                roubos: 0
            }, {
                id: 1,
                nome: 'insira um jogador',
                imagem_url: '',
                fator_x: '2',
                numero_camisa: '+',
                pontuacao: 0,
                cestas_3: 0,
                cestas_2: 0,
                cestas_1: 0,
                faltas: 0,
                rebotes: 0,
                assistencias: 0,
                roubos: 0
            }, {
                id: 1,
                nome: 'insira um jogador',
                imagem_url: '',
                fator_x: '2',
                numero_camisa: '+',
                pontuacao: 0,
                cestas_3: 0,
                cestas_2: 0,
                cestas_1: 0,
                faltas: 0,
                rebotes: 0,
                assistencias: 0,
                roubos: 0
            },],
        time_b: [
            {
                id: 1,
                nome: 'insira um jogador',
                imagem_url: '+',
                fator_x: '2',
                numero_camisa: '+',
                pontuacao: 0,
                cestas_3: 0,
                cestas_2: 0,
                cestas_1: 0,
                faltas: 0,
                rebotes: 0,
                assistencias: 0,
                roubos: 0
            }, {
                id: 1,
                nome: 'insira um jogador',
                imagem_url: '',
                fator_x: '2',
                numero_camisa: '+',
                pontuacao: 0,
                cestas_3: 0,
                cestas_2: 0,
                cestas_1: 0,
                faltas: 0,
                rebotes: 0,
                assistencias: 0,
                roubos: 0
            }, {
                id: 1,
                nome: 'insira um jogador',
                imagem_url: '',
                fator_x: '2',
                numero_camisa: '+',
                pontuacao: 0,
                cestas_3: 0,
                cestas_2: 0,
                cestas_1: 0,
                faltas: 0,
                rebotes: 0,
                assistencias: 0,
                roubos: 0
            }, {
                id: 1,
                nome: 'insira um jogador',
                imagem_url: '',
                fator_x: '2',
                numero_camisa: '+',
                pontuacao: 0,
                cestas_3: 0,
                cestas_2: 0,
                cestas_1: 0,
                faltas: 0,
                rebotes: 0,
                assistencias: 0,
                roubos: 0
            }, {
                id: 1,
                nome: 'insira um jogador',
                imagem_url: '',
                fator_x: '2',
                numero_camisa: '+',
                pontuacao: 0,
                cestas_3: 0,
                cestas_2: 0,
                cestas_1: 0,
                faltas: 0,
                rebotes: 0,
                assistencias: 0,
                roubos: 0
            },]
    }
});